# Copilot Setup Steps
# This file configures the environment for GitHub Copilot coding agent.
# Copilot uses these steps to set up the development environment before working on issues.

steps:
  # Install Node.js dependencies
  - name: Install dependencies
    run: npm install

  # Configure Firebase Emulator for local development
  # This ensures all Copilot tasks use emulator instead of requiring Firebase credentials
  - name: Configure Firebase Emulator
    run: |
      cp .env.example .env.local
      if grep -q '^VITE_USE_FIREBASE_EMULATOR=' .env.local; then
        sed -i 's/^VITE_USE_FIREBASE_EMULATOR=.*/VITE_USE_FIREBASE_EMULATOR=true/' .env.local
      else
        echo "VITE_USE_FIREBASE_EMULATOR=true" >> .env.local
      fi
      # Add placeholder Firebase credentials for emulator mode
      echo "VITE_FIREBASE_API_KEY=demo-api-key" >> .env.local
      echo "VITE_FIREBASE_AUTH_DOMAIN=localhost" >> .env.local
      echo "VITE_FIREBASE_PROJECT_ID=demo-certlab" >> .env.local

  # Start Firebase Emulators in background
  - name: Start Firebase Emulators
    run: npm run emulators:start
    background: true

  # Wait for emulators to be ready
  - name: Wait for emulators
    run: |
      echo "Waiting for Firebase Emulators to start..."
      timeout 30 bash -c 'until curl -s http://localhost:4000 > /dev/null; do sleep 1; done'
      echo "✓ Firebase Emulators ready"

  # Seed emulator with test data
  - name: Seed emulator data
    run: npm run emulators:seed

  # Verify the build works
  - name: Build project
    run: npm run build

  # Run tests to ensure environment is working
  - name: Run tests
    run: npm run test:run
